#!/bin/sh
git clone https://github.com/admarschoonen/dESPatch-web.git
cd dESPatch-web
python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt

echo -n "export SECRET_KEY=" > .env
python3 -c "import uuid; print(uuid.uuid4().hex)" >> .env
cat >> .env << EOF
export MAIL_SERVER=localhost
export MAIL_PORT=25
export FLASK_APP=dESPatch-web.py
export SERVERNAME=SERVERNAME-NOT-SET
EOF

flask db init
flask db migrate -m "init"
flask db upgrade

echo "[program:dESPatch-web]" > dESPatch-web.conf
echo "`pwd`/venv/bin/gunicorn -b localhost:8000 -w 4 dESPatch-web:app" >> dESPatch-web.conf
echo "directory=`pwd`" >> dESPatch-web.conf
cat >> dESPatch-web.conf << EOF
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
EOF

echo "#!/bin/sh" > dESPatch-web.sh
echo "cd `pwd`" >> dESPatch-web.sh
cat >> dESPatch-web.sh << EOF
. venv/bin/activate
. ./.env
gunicorn -b localhost:5000 -w 4 dESPatch-web:app
EOF
chmod a+x dESPatch-web.sh

echo "Set SERVERNAME in .env, then start the application with:"
echo "  FIXME: systemd unit file for dESPatch-web.sh"
echo ""
echo "Next: change admin password and create root certificate:"
echo "  change password: login as user admin with password admin and change the password in your profile"
echo "  create root certificate: FIXME: description for how to retrieve certificate from firefox"

