#!/bin/sh
git clone https://github.com/admarschoonen/dESPatch-web.git
cd dESPatch-web
python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt

echo -n "SECRET_KEY=" > .env
python3 -c "import uuid; print(uuid.uuid4().hex)" >> .env
cat >> .env << EOF
MAIL_SERVER=localhost
MAIL_PORT=25
FLASK_APP=dESPatch-web.py
SERVERNAME=SERVERNAME-NOT-SET
EOF

flask db init
flask db migrate -m "init"
flask db upgrade

echo "[program:dESPatch-web]" > dESPatch-web.conf
echo "`pwd`/venv/bin/gunicorn -b localhost:8000 -w 4 dESPatch-web:app" >> dESPatch-web.conf
echo "directory=`pwd`" >> dESPatch-web.conf
cat >> dESPatch-web.conf << EOF
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
EOF

# echo "#!/bin/sh" > dESPatch-web.sh
# echo "cd `pwd`" >> dESPatch-web.sh
# cat >> dESPatch-web.sh << EOF
# . venv/bin/activate
# gunicorn -b localhost:5000 -w 4 dESPatch-web:app
# EOF
# chmod a+x dESPatch-web.sh

# cat > dESPatch-web.service << EOF
# [Unit]
# Description=dESPatch-web service
# 
# [Service]
# EOF
# echo "ExecStart=`pwd`/dESPatch-web.sh" >> dESPatch-web.service
# cat >> dESPatch-web.service << EOF
# 
# [Install]
# WantedBy=multi-user.target
# EOF

cat > dESPatch-web.service << EOF
[Unit]
Description=dESPatch-web service
After=network-online.target

[Service]
Type=simple
User=admar
Group=admar
EOF
echo "WorkingDirectory=`pwd`" >> dESPatch-web.service
echo "EnvironmentFile=`pwd`/.env" >> dESPatch-web.service
echo "ExecStart=`pwd`/venv/bin/gunicorn -b localhost:5000 -w 4 dESPatch-web:app" >> dESPatch-web.service
cat >> dESPatch-web.service << EOF
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF

sudo cp dESPatch-web.service /etc/systemd/system
sudo systemctl enable dESPatch-web

cat << EOF
Set SERVERNAME in .env, then start the application with:
 sudo systemctl start dESPatch-web

After that: change admin password and create root certificate:
* change password: 
  * login as user admin with password admin 
  * change the password in your profile
* create root certificate: 
  * open the website with Firefox and click on the lock icon left of the URL
  * click on the arrow to show connection details and click 'More Information'
  * click on the security tab and then on 'View Certificate'; this will open a new tab
  * click on the root certificate and then under Download click on 'PEM (cert)'
  * save the downloaded file in this folder with name 'cert.txt'
EOF
