#!/bin/sh
git clone https://github.com/admarschoonen/dESPatch-web.git
cd dESPatch-web
python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt

echo -n "export SECRET_KEY=" > .env
python3 -c "import uuid; print(uuid.uuid4().hex)" >> .env
cat >> .env << EOF
export MAIL_SERVER=localhost
export MAIL_PORT=25
export FLASK_APP=dESPatch-web.py
export SERVERNAME=SERVERNAME-NOT-SET
EOF

flask db init
flask db migrate -m "init"
flask db upgrade

echo "[program:dESPatch-web]" > dESPatch-web.conf
echo "`pwd`/venv/bin/gunicorn -b localhost:8000 -w 4 dESPatch-web:app" >> dESPatch-web.conf
echo "directory=`pwd`" >> dESPatch-web.conf
cat >> dESPatch-web.conf << EOF
user=ubuntu
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
EOF

echo "Start the application with:"
echo "  gunicorn -b localhost:8000 -w 4 dESPatch-web:app"
echo ""
echo "Alternatively, copy dESPatch-web.conf to /etc/supervisor/conf.d/ and run:"
echo "  sudo supervisorctl reload"

