#!/bin/sh
git clone https://github.com/admarschoonen/dESPatch-web.git
cd dESPatch-web
python3 -m venv venv
source venv/bin/activate
pip3 install -r requirements.txt

echo -n "SECRET_KEY=" > .env
python3 -c "import uuid; print(uuid.uuid4().hex)" >> .env
cat >> .env << EOF
MAIL_SERVER=localhost
MAIL_PORT=25
DATABASE_URL=sqlite
EOF

echo "export FLASK_APP=dESPatch-web.py" >> ~/.profile
